Implement form submission
mr-fox93/panini-creator pull request #10
Opened 2023-11-11 18:01 UTC by mr-fox93

2023-11-11 18:03 UTC, NerdbordMentor requested changes
## Code Review Report

### Task Requirements Validation

1. Clicking on **Place order** button should send form payload to required endpoint. After successful request, image URL of ordered panini should be returned.

The code changes in `BaseForm.tsx` show that the form submission now sends a POST request to the required endpoint with the correct headers and body format. The response is also handled correctly, with the image URL being extracted from the response data.

2. Clicking on **Place order** button redirect to **Success screen** when form submission request is successful.

The `navigate` function is used to redirect to the success screen upon a successful request. The image URL is passed as state to the success screen.

3. When user enters **Success screen** it should automatically download image of ordered Panini

This requirement cannot be validated as the code changes for the Success screen were not provided.

### Code Improvements Suggestions

1. Error Handling: In `BaseForm.tsx`, the fetch request could benefit from better error handling. Currently, if the request fails, an error is logged to the console but the user isn't notified of the failure. Consider adding user-friendly error messages.

2. Code Duplication: In `CheeseSelect.tsx` and `DressingCarousel.tsx`, there is some code duplication when setting visibility and updating state. Consider creating a helper function to handle these updates.

3. Unused Code: In `DressingCarousel.tsx`, there are commented out lines of code. It's good practice to remove unused code to keep the codebase clean and readable.

4. Unnecessary Comments: In `BaseForm.tsx`, there are commented out lines of code that seem unnecessary. Consider removing these comments to improve code readability.

5. Code Organization: The `onSubmit` function in `BaseForm.tsx` is quite large and does several things. Consider breaking it down into smaller, more manageable functions.

6. Unused Variables: In `BaseForm.tsx`, the `formRef` variable is declared but never used. Consider removing unused variables to keep the code clean and efficient.

7. Styling Consistency: In `BaseForm.styles.ts`, the changes made to the height properties of `Cheese` and `Dressing` are inconsistent with the rest of the codebase. Consider maintaining consistency in your styling approach.

8. Type Definitions: In `DressingCarousel.tsx`, the type `CarouselState` could be better named to reflect that it's an array of carousels, not a single carousel state. Consider renaming it to `CarouselsState` or similar.

9. Component Exporting: In `PlaceOrderBtn.tsx`, the component is exported at the bottom of the file, which is inconsistent with other components like `FinalizeOrder.tsx` where the component is exported inline. Consider maintaining consistency in your component exporting approach.

2023-11-11 18:14 UTC, NerdbordMentor requested changes
## Code Review Report

### Task Requirements Validation

1. Clicking on **Place order** button should send form payload to required endpoint. After successful request, image URL of ordered panini should be returned.

The code changes in `BaseForm.tsx` show that the form submission is now handled by a `fetch` request to the required endpoint. The request method is `POST`, and the headers and body are correctly set. However, the response handling does not seem to handle the image URL of the ordered panini. The code only logs the response data and navigates to the success screen. This part of the requirement is not fully covered.

2. Clicking on **Place order** button redirect to **Success screen** when form submission request is successful.

The code changes in `BaseForm.tsx` show that after a successful form submission, the user is redirected to the success screen. This part of the requirement is covered.

3. When user enters **Success screen** it should automatically download image of ordered Panini

There are no code changes related to this requirement, so it's not covered.

### Suggestions for Improvement

1. Handle the image URL of the ordered panini:

After the successful form submission, you should handle the image URL that is returned in the response. You could store it in a state or pass it as a parameter when navigating to the success screen.

```javascript
.then((data) => {
  console.log("Success:", data);
  // Store or pass the image URL
  const imageUrl = data.imageUrl;
  navigate("/success", { state: { imageUrl } });
})
```

2. Implement automatic image download on the success screen:

On the success screen, you should implement an effect that triggers the download of the image when the screen is entered. You can use the `useEffect` hook for this.

```javascript
// SuccessScreen.tsx
import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';

const SuccessScreen = () => {
  const location = useLocation();
  const imageUrl = location.state.imageUrl;

  useEffect(() => {
    // Trigger image download
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = 'ordered-panini.jpg';
    link.click();
  }, [imageUrl]);

  // ...
};
```

3. Error handling:

The current implementation of the form submission does not provide any feedback to the user when the request fails. You should add error handling that informs the user when something goes wrong.

```javascript
.catch((error) => {
  console.error("Error:", error);
  // Inform the user about the error
});
```

4. Code cleanup:

There are some commented-out lines of code in `DressingCarousel.tsx` and `PlaceOrderBtn.tsx` that should be removed.

5. Unused variables:

The `formRef` variable in `BaseForm.tsx` and the `useNavigate` import in `PlaceOrderBtn.tsx` are not used and should be removed.

6. Styling:

The styling changes in `BaseForm.styles.ts` and `CheeseSelect.tsx` do not seem to be related to the task requirements. Make sure these changes are necessary and do not break the existing layout.

2023-11-13 13:58 UTC, Sumick approved these changes
Nerdy was right - image downloading should happen in the success screen :-) But let's consider your solution ok, as it's not making any real difference in current flow :D

2023-11-13 13:58 UTC, Sumick commented on src/components/ConfigureBase/MeatSelect.tsx
> +const DropdownsContainer = styled.div<DropdownContainerProps>`
**praise:** Good job with typing this

2023-11-13 13:58 UTC, Sumick commented on src/components/ConfigureBase/MeatSelect.tsx
> +// import { useFormContext } from "react-hook-form";
**nitpick:** Comments to remove

2023-11-13 13:58 UTC, Sumick commented on src/components/BaseForm/BaseForm.tsx
> +          window.open(data.imageUrl, "_blank");
**nitpick:** Yea, Nerdy wasn't approving because download is not happening in Success screen as described in task requirements :)

2023-11-13 13:58 UTC, Sumick commented on src/components/BaseForm/BaseForm.tsx
> +        console.log("Success:", data);
**nitpick:** Log to remove

2023-11-15 12:44 UTC, merged