implement hook forms
mr-fox93/panini-creator pull request #8
Opened 2023-11-08 12:49 UTC by mr-fox93

2023-11-08 12:51 UTC, NerdbordMentor requested changes
Based on the provided task requirements and the code changes, it's impossible to conduct a proper code review. The task was to integrate the React Hook Form library into the form UI, but the provided code changes only show the removal of a comment line in the `onSubmit` function. 

There are no changes related to the integration of React Hook Form. The requirements specify that React Hook Form must be used and integrated into the existing UI, but there's no evidence of this in the provided code changes.

Please provide all relevant code changes related to the task requirements for a comprehensive review.

2023-11-09 12:33 UTC, Sumick approved these changes
Looks good, I've listed few improvements to consider

2023-11-09 12:33 UTC, Sumick commented on src/components/CheeseSelect.tsx
> +      setValue(`base.cheese`, newOptions, { shouldValidate: true });
**nitpick:** I would keep form keys in some `const` or `enum` to prevent duplicating string values. It will be hard to maintain them this way

2023-11-09 12:33 UTC, Sumick commented on src/components/CheeseSelect.tsx
> +          style={{ marginRight: "10px" }}
**nitpick:** we should avoid writing inline styles

2023-11-09 12:33 UTC, Sumick commented on src/components/ConfigureExtras/Topping.tsx
> +export const toppingSchema = z
**nitpick:** I would keep all schemas in one place, like `form.schemas.ts`

2023-11-09 12:33 UTC, Sumick commented on src/components/ConfigureExtras/Topping.tsx
> +    const newTopping = topping === "SESAME" ? null : "SESAME";
**nitpick:** You have duplicated strings - would be beneficial to keep such values in some const or enum

2023-11-09 12:33 UTC, Sumick commented on src/components/BaseForm/BaseForm.styles.ts
> +  //height: 79px;
**nitpick:** comment to remove

2023-11-09 13:41 UTC, merged